### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by BrandDogs** [arsenaltech/nova-tab#1]
Hi,

Im getting the fllowing error on using this package.

Class name must be a valid object or a string {"userId":1,"email":"jurn@xx.nl","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class name must be a valid object or a string at /home/jurn/Documenten/sites/planning/nova/src/Http/Requests/InteractsWithRelatedResources.php:20)

**Comment by shabbirbharmal** [comment]
Can you please share how your fields method of Nova resource look like?

**Comment by BrandDogs** [comment]
Nevermind, i got it working. Thanks.

**Comment by BrandDogs** [comment]
Just got the same message again, with the following code:


new NovaTab('Overig',[


  ]),

**Comment by shabbirbharmal** [comment]
So is it throwing this error even when your second argument to Tab constructor is array of fields instead of empty array?

**Comment by BrandDogs** [comment]
yes, on both occasions.

**Comment by FreekVR** [comment]
Yes it appears that the "viaResource" attribute in the URL that is used to load in MorphMany or BelongstoMany relationships is being skipped when tabs are used to display a resource. I'm thinking it's a Vue prop that's getting lost somewhere along the way.

**Comment by KarimQaderi** [comment]
It also showed me the message


nova/src/Nova.php

```

public static function newResourceFromModel($model)
    {
        $resource = static::resourceForModel($model);
        if($resource == null)
            return $model;

        return new $resource($model);
    }

```

add
```
if($resource == null)
            return $model;

```

**Comment by shabbirbharmal** [comment]
> Just got the same message again, with the following code:
> 
> new NovaTab('Overig',[
> 
> ]),

I am not able to reproduce this issue. Probably something specific to your setup? If you are still facing this issue and willing to share your resource class I can take a look at it.

**Comment by shabbirbharmal** [comment]
> Yes it appears that the "viaResource" attribute in the URL that is used to load in MorphMany or BelongstoMany relationships is being skipped when tabs are used to display a resource. I'm thinking it's a Vue prop that's getting lost somewhere along the way.

This issue is fixed and I believe it's not related to what @BrandDogs is facing.
