### ISSUE TITLE
Panel inside a nova tab?

### ISSUE THREAD

**Issue by XGhozt** [arsenaltech/nova-tab#10]
This package is awesome! I'm just wondering how I can get Panels to work inside of a tab. At the very least, show the title so it keeps things grouped inside the tab. Is this disabled specifically or is am I formatting the code incorrectly?

https://nova.laravel.com/docs/1.0/resources/fields.html#field-panels

**Comment by shabbirbharmal** [comment]
Yes it is disabled intentionally because the way it is implemented it contradicts each other. That being said I will give another look at it when I get chance and see if it can be implemented in a different way.

**Comment by XGhozt** [comment]
Thanks @shabbirbharmal -- I think it would be fine to just insert the titles above each group of fields. Maybe an h2 or h3, so they are spaced out a bit. I don't think it needs any wrapping divs.

**Comment by shabbirbharmal** [comment]
Good idea! Just pushed simple nova field to add headers

https://github.com/arsenaltech/nova-header

**Comment by XGhozt** [comment]
That works too, thanks!
