### ISSUE TITLE
Full width and height tabs

### ISSUE THREAD

**Issue by tobeycodes** [arsenaltech/nova-tab#21]
We could add `margin: -.75em -1.5em;` to the `.tab-component`. I'd prefer if we could just remove the padding and background from the `.card` but not sure how to do that without it affecting global styles.

This looks way better in my opinion

<img width="1296" alt="screenshot 2018-11-04 16 11 40" src="https://user-images.githubusercontent.com/3613405/47969922-5996ee00-e04c-11e8-9e81-9b8ab1beb2f7.png">

**Comment by tanthammar** [comment]
+1 for this suggestion, (I don't know how to achieve this either ... )
