### ISSUE TITLE
Class 'Arsenaltech\NovaTab\Resource' not found

### ISSUE THREAD

**Issue by fabiobettiol** [arsenaltech/nova-tab#23]
\Nova\Resource.php:

```
<?php

namespace App\Nova;

use Laravel\Nova\Resource as NovaResource;
use Laravel\Nova\Http\Requests\NovaRequest;

use Arsenaltech\NovaTab\Resource as TabResource;

abstract class Resource extends TabResource
{
...
```

**Comment by shabbirbharmal** [comment]
Please review updated readme on github. We are trait instead of Arsenaltech\NovaTab\Resource 

Add the Tabs trait to your App\Nova\Resource class.

``use Arsenaltech\NovaTab\Tabs;

abstract class Resource extends NovaResource
{
    use Tabs;

**Comment by fabiobettiol** [comment]
Thank you. I will
