### ISSUE TITLE
Problem with HasMany

### ISSUE THREAD

**Issue by daguilarm** [arsenaltech/nova-tab#8]
When create a new resource from a relationship (HasMany):

![captura1-1](https://user-images.githubusercontent.com/2663941/46258947-5d29d900-c4d2-11e8-94a6-1457c8df1631.jpg)

The default value for the relationship is null:

![captura-1-2](https://user-images.githubusercontent.com/2663941/46258968-92362b80-c4d2-11e8-858b-efa71c3d7677.jpg)

Because nova block the option from the select, it is impossible to change the value from the select. 
I have tried to do the same without using the tab, and it works. The default value is lost within the tab code.

**Comment by daguilarm** [comment]
Sorry for close the issue, It is a nova-tab problem. When create a resource from inside a tab (detail view) and the target resource use nova-tabs, the default value for the relationship its null.

**Comment by shabbirbharmal** [comment]
This issue is fixed. Thank you for reporting it
