### ISSUE TITLE
Right now, only show one field for tab...

### ISSUE THREAD

**Issue by daguilarm** [arsenaltech/nova-tab#9]
This morning the tabs system has started to fail. Only shows one result per tab:

<img width="1657" alt="captura de pantalla 2018-10-02 a las 10 12 51" src="https://user-images.githubusercontent.com/2663941/46336695-ddb01d00-c62b-11e8-82c7-0689ca6d1a92.png">

<img width="1640" alt="captura de pantalla 2018-10-02 a las 10 12 58" src="https://user-images.githubusercontent.com/2663941/46336707-e143a400-c62b-11e8-818b-63a13e407e11.png">

<img width="1648" alt="captura de pantalla 2018-10-02 a las 10 13 04" src="https://user-images.githubusercontent.com/2663941/46336716-e4d72b00-c62b-11e8-9209-e0be51051d77.png">

Just only one field per tab... the other fields are missing. Maybe the last nova update? or the last commit with the html feature? I tested the application before the last commit and was ok...

**Comment by daguilarm** [comment]
Confirmed, it's the last commit. Currently working perfectly with the versión:

dev-master#95e93236988eb5011a0449dbe2d8d3c35f8ceeb6

**Comment by shabbirbharmal** [comment]
This is fixed in latest commit

**Comment by bigperson** [comment]
Hi. I have some problem on dev-master#578e8c8a90aedd9d957e3ba67bb37beb4e9958b9
@shabbirbharmal

**Comment by shabbirbharmal** [comment]
What is it? Are you still seeing only one field per tab?

**Comment by bigperson** [comment]
@shabbirbharmal yes

**Comment by mariapaulinar** [comment]
I have same poblem :(

**Comment by mariapaulinar** [comment]
I have the same problem :(
